layout: stacked
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 9
  exclude:
    archived: false
    forks: true
    projects:
    # - repo-name

social_media:
  # behance: your_username
  # dribbble: your_username
  # facebook: your_username
  # hackerrank: your_username
  instagram: widdyjp
  # keybase: your_username
  linkedin: widdyjp
  # mastodon: your_username
  medium: widdyjp
  # stackoverflow: your_user_id
  # telegram: your_username
  twitter: widdyjp
  # unsplash: your_username
  # vk: your_username
  # website: http://your_website_url
  # youtube: your_username

topics:
  - name: Android
    web_url: https://developer.android.com
    image_url: https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcS0Ec2BeChxHchET9_p5iAhVLwzgGjYl_EV8P_P9zN8b4AgKB4o

  - name: Node.js
    web_url": https://nodejs.org/en
    image_url: https://nodejs.org/static/images/logo.svg

  - name: ASP.NET
    web_url: https://dotnet.microsoft.com/apps/aspnet
    image_url: https://upload.wikimedia.org/wikipedia/commons/thumb/e/ee/.NET_Core_Logo.svg/768px-.NET_Core_Logo.svg.png
